#! /usr/bin/env bash
#
# Scripts location
scriptLoc='/.dotfiles/system/programs/suckless/dmenu/scripts/'

# Options array
declare -a options=(
  "dmpower"
  "dmnix"
)

# Number of items in options array
optionsSize=${#options[@]}

# User prompt
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l $optionsSize -p 'dmmenu:')

# Execution
bash $HOME"${scriptLoc}${choice}"
