#! /usr/bin/env bash

# Options array
declare -a options=(
  "Lock"
  "Suspend"
  "Shut Down"
  "Restart"
  "Logout"
)

# Confirm array
declare -a confirm=(
  "Yes"
  "No"
)

# Size of arrays
optionsSize=${#options[@]}
confirmSize=${#confirm[@]}

# User prompt
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l $optionsSize -p 'Power Options:')

# Execution
if [ "$choice" == "Lock" ]; then
  slock

elif [ "$choice" == "Suspend" ]; then
  systemctl suspend
  slock

elif [ "$choice" == "Shut Down" ]; then
  confirm=$(printf '%s\n' "${confirm[@]}" | dmenu -i -l $confirmSize -p 'Shut Down?:')

  if [ "$confirm" == "Yes" ]; then
    poweroff
  fi

elif [ "$choice" == "Restart" ]; then
  confirm=$(printf '%s\n' "${confirm[@]}" | dmenu -i -l $confirmSize -p 'Restart?:')

  if [ "$confirm" == "Yes" ]; then
    reboot
  fi

elif [ "$choice" == "Logout" ]; then
  confirm=$(printf '%s\n' "${confirm[@]}" | dmenu -i -l $confirmSize -p 'Logout?:')

  if [ "$confirm" == "Yes" ]; then
    killall dwm
  fi
fi
