#+title: dmenu Scripts

* About
Collection of dmenu scripts used.

* Table of contents :toc:
- [[#about][About]]
- [[#scripts][Scripts]]
  - [[#dmtemplate][dmtemplate]]
  - [[#dmmenu][dmmenu]]
  - [[#dmnix][dmnix]]
  - [[#dmpower][dmpower]]
  - [[#dmfirefox][dmfirefox]]

* Scripts
** dmtemplate
Template for scripts.

*** Options and confirmation array
Specify options array. Optionally, you can also include a confirmation array, for cases where the user would want to confirm before excuting a command (e..g, poweroff, logout).

#+begin_src shell :tangle dmtemplate
#! /usr/bin/env bash

# Options array
declare -a options=(
  "Option 1"
  "Option 2"
  "Option 3"
)

# Confirm array
declare -a confirm=(
  "Yes"
  "No"
)
#+end_src

This counts the number of items in the array. This count is used to determine the height of dmenu to match the number of options in the array.

#+begin_src shell :tangle dmtemplate
#Size of arrays
optionsSize=${#options[@]}
confirmSize=${#confirm[@]}
#+end_src

*** Piping options array to dmenu
This will pipe the options array to dmenu and store the user's choice in the ~choice~ variable.

We use ~printf '%s\n'~ to format the array to one item to a line. You can change ~Title~ to what will prompted by dmenu.

#+begin_src shell :tangle dmtemplate
# User prompt
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l $optionsSize -p 'Title:')
#+end_src

*** Execution
The user's choice will determine the output executed.

We can also optionally prompt the user to confirm their selection before executing the output. Note that if they don't select ~Yes~, dmenu will close.

#+begin_src shell :tangle dmtemplate
# Execution
if [ "$choice" == "Option 1" ]; then
  output 1
elif [ "$choice" == "Option 2" ]; then
  output 2

elif [ "$choice" == "Option 3" ]; then
  confirm=$(printf '%s\n' "${confirm[@]}" | dmenu -i -l $confirmSize -p 'Confirm Option 3?:')

  if [ "$confirm" == "Yes" ]; then
    output 3
  fi
fi
#+end_src

** dmmenu
A general dmenu to access other dmenus.

*** Scripts location
This defines where the dmenu scripts are stored, so that we can reference them when calling them.

#+begin_src shell :tangle dmmenu
#! /usr/bin/env bash
#
# Scripts location
scriptLoc='/.dotfiles/system/programs/suckless/dmenu/scripts/'
#+end_src

*** Options array
#+begin_src shell :tangle dmmenu
# Options array
declare -a options=(
  "dmpower"
  "dmnix"
)

# Number of items in options array
optionsSize=${#options[@]}
#+end_src

*** Piping options to dmenu
#+begin_src shell :tangle dmmenu
# User prompt
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l $optionsSize -p 'dmmenu:')
#+end_src

*** Execution
Executes the script chosen. Note that the option must be in the [[*Scripts location]] defined above.

#+begin_src shell :tangle dmmenu
# Execution
bash $HOME"${scriptLoc}${choice}"
#+end_src

** TODO dmnix
dmenu for NixOS related tasks, such as rebuilding (both system wide and per user), updating flakes, updating channels, etc.

*** Options and confirmation array
Specify options array. Optionally, you can also include a confirmation array, for cases where the user would want to confirm before excuting a command (e..g, poweroff, logout).

#+begin_src shell :tangle dmnix
#! /usr/bin/env bash

# Options array
declare -a options=(
  "System rebuild"
  "User rebuild"
  "Full rebuild"
  "TODO Garbage collection"
  "TODO Update packages"
)

# Confirm array
declare -a confirm=(
  "Yes"
  "No"
)
#+end_src

This counts the number of items in the array. This count is used to determine the height of dmenu to match the number of options in the array.

#+begin_src shell :tangle dmnix
#Size of arrays
optionsSize=${#options[@]}
confirmSize=${#confirm[@]}
#+end_src

*** Piping options array to dmenu
This will pipe the options array to dmenu and store the user's choice in the ~choice~ variable.

We use ~printf '%s\n'~ to format the array to one item to a line. You can change ~Title~ to what will prompted by dmenu.

#+begin_src shell :tangle dmnix
# User prompt
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l $optionsSize -p 'Nix:')
#+end_src

*** Execution
The user's choice will determine the output executed.

We can also optionally prompt the user to confirm their selection before executing the output. Note that if they don't select ~Yes~, dmenu will close.

#+begin_src shell :tangle dmnix
# Execution
if [ "$choice" == "System rebuild" ]; then
  confirm=$(printf '%s\n' "${confirm[@]}" | dmenu -i -l $confirmSize -p 'Confirm SYSTEM rebuild?:')

  if [ "$confirm" == "Yes" ]; then
    st -e sh -c '
     bash ~/.dotfiles/scripts/nixrebuild.sh
     read;'
  fi

elif [ "$choice" == "User rebuild" ]; then
  confirm=$(printf '%s\n' "${confirm[@]}" | dmenu -i -l $confirmSize -p 'Confirm USER rebuild?:')

  if [ "$confirm" == "Yes" ]; then
    st -e sh -c '
     bash ~/.dotfiles/scripts/homerebuild.sh
     read;'
  fi

elif [ "$choice" == "Full rebuild" ]; then
  confirm=$(printf '%s\n' "${confirm[@]}" | dmenu -i -l $confirmSize -p 'Confirm FULL rebuild?:')

  if [ "$confirm" == "Yes" ]; then
    st -e sh -c '
     bash ~/.dotfiles/scripts/nixrebuild.sh
     bash ~/.dotfiles/scripts/homerebuild.sh
     printf ">>> Full rebuild: DONE\n";
     printf "Press any button to EXIT"
     read;'
  fi

elif [ "$choice" == "Option 3" ]; then
  confirm=$(printf '%s\n' "${confirm[@]}" | dmenu -i -l $confirmSize -p 'Confirm Option 3?:')

  if [ "$confirm" == "Yes" ]; then
    output 3
  fi
fi
#+end_src

** dmpower
Power options

*** Options and confirmation array
#+begin_src shell :tangle dmpower
#! /usr/bin/env bash

# Options array
declare -a options=(
  "Lock"
  "Suspend"
  "Shut Down"
  "Restart"
  "Logout"
)

# Confirm array
declare -a confirm=(
  "Yes"
  "No"
)
#+end_src

Size of arrays.

#+begin_src shell :tangle dmpower
# Size of arrays
optionsSize=${#options[@]}
confirmSize=${#confirm[@]}
#+end_src

*** Piping array to dmenu
We use "printf '%s\n'" to format the array one item to a line.

#+begin_src shell :tangle dmpower
# User prompt
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l $optionsSize -p 'Power Options:')
#+end_src

*** Execution
~slock~ locks the screen.

#+begin_src shell :tangle dmpower
# Execution
if [ "$choice" == "Lock" ]; then
  slock
#+end_src

~Suspend~ puts the computer to sleep. We have also configured it so that it also locks the computer before putting it to sleep. Note that if execute ~slock~, the computer won't suspend as it waits for ~slock~ to close before. For some reason, calling ~slock~ afterwards results in the intended behavior.

#+begin_src shell :tangle dmpower
elif [ "$choice" == "Suspend" ]; then
  systemctl suspend
  slock
#+end_src

~Shut Down~ shuts down the computer. dmenu will prompt the user to confirm this choice before executing.

#+begin_src shell :tangle dmpower
elif [ "$choice" == "Shut Down" ]; then
  confirm=$(printf '%s\n' "${confirm[@]}" | dmenu -i -l $confirmSize -p 'Shut Down?:')

  if [ "$confirm" == "Yes" ]; then
    poweroff
  fi
#+end_src

~Restart~ will reboot the computer. dmenu will prompt the user to confirm this choice before executing.

#+begin_src shell :tangle dmpower
elif [ "$choice" == "Restart" ]; then
  confirm=$(printf '%s\n' "${confirm[@]}" | dmenu -i -l $confirmSize -p 'Restart?:')

  if [ "$confirm" == "Yes" ]; then
    reboot
  fi
#+end_src

~Logout~ is meant to end the current session. Right now, it just closes dwm, which looks like the intended purpose as we only have one user.

#+begin_src shell :tangle dmpower
elif [ "$choice" == "Logout" ]; then
  confirm=$(printf '%s\n' "${confirm[@]}" | dmenu -i -l $confirmSize -p 'Logout?:')

  if [ "$confirm" == "Yes" ]; then
    killall dwm
  fi
fi
#+end_src

** dmfirefox
Opens specific firefox proframs.

*** Options and confirmation array
Specify options array. Optionally, you can also include a confirmation array, for cases where the user would want to confirm before excuting a command (e..g, poweroff, logout).

#+begin_src shell :tangle dmfirefox
#! /usr/bin/env bash

# Options array
declare -a options=(
  "default"
  "Gong Cha"
)
#+end_src

This counts the number of items in the array. This count is used to determine the height of dmenu to match the number of options in the array.

#+begin_src shell :tangle dmfirefox
#Size of arrays
optionsSize=${#options[@]}
#+end_src

*** Piping options array to dmenu
This will pipe the options array to dmenu and store the user's choice in the ~choice~ variable.

We use ~printf '%s\n'~ to format the array to one item to a line.

#+begin_src shell :tangle dmfirefox
# User prompt
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l $optionsSize -p 'Firefox Profile:')
#+end_src

*** Execution
The user's choice will determine the output executed.

#+begin_src shell :tangle dmfirefox
# Execution
if [ -z "$choice" ]; then
   exit
else
   firefox -P -no-remote "$choice"
fi
#+end_src

