#+title: dwm Config
#+property: header-args :tangle config.h

* About
boscOS uses dmw, an extremely fast, small, and dynamic window manager for X. I am using ~dwm 6.5~.

The configuration of dwm is done by changing files in ~config.h~ and recompiling the source code. In NixOS, this is done by rebuilding.

* Table of contents :toc:
- [[#about][About]]
- [[#appearance][Appearance]]
  - [[#windows][Windows]]
  - [[#topbar][Topbar]]
  - [[#colors][Colors]]
  - [[#layout-symbols][Layout symbols]]
- [[#tagging][Tagging]]
  - [[#tag-names][Tag names]]
  - [[#tag-labels][Tag labels]]
  - [[#default-for-applications][Default for applications]]
  - [[#window-following][Window following]]
- [[#layout-options][Layout options]]
  - [[#master-and-focus][Master and focus]]
- [[#shortcuts][Shortcuts]]
  - [[#definitions][Definitions]]
  - [[#aliases][Aliases]]
  - [[#keyboard-shortcuts][Keyboard shortcuts]]
  - [[#mouse-buttons][Mouse buttons]]

* Appearance
These values change what dwm looks like.

** Windows
- ~borderpx~, defines the width of window borders in pixels.
- ~snap~, defines how close dragged windows need to be to an edge to snap to them.
- ~gappx~, defines the width of the gap between windows in tile mode in pixels. We have a [[http://dwm.suckless.org/patches/fullgaps/][patch]] that adds key bindings to adjust this value while dwm is running.
- ~gappxMin~, is defines the minimum size of the gaps. By default, this takes the initial value of ~gappx~.

#+begin_src c
/* APPEARANCE */

// Windows
static const unsigned int borderpx      = 3;      /* width of window borders */
static const unsigned int snap          = 5;      /* proximity for edge snap */
static const unsigned int gappx         = 10;     /* width of gaps between windows */
static const unsigned int gappxMin      = gappx;  /* minimum size of gaps */
#+end_src

** Topbar
- ~showbar~, ~1~ means show bar. ~0~ means no bar.
- ~topbar~, ~1~ means the bar will appear at the top. ~0~ means the bar will appear at the bottom.
- ~font~, defines the font used in the topbar.

#+begin_src c
// Topbar
static const int showbar            = 1;                        /* 0 means no bar */
static const int topbar             = 0;                        /* 0 means bottom bar */
static const char *fonts[]          = { "monospace:size=10" };  /* topbar font */
#+end_src

** Colors
Hex code for colors are stored in variables, which are used in the Scheme array. Each column defines the,

- ~fg~, font
- ~bg~, background
- ~border~, window borders

for the,

- ~SchemeNorm~, normal/default tag/window
- ~SchemeSel~, selected tag/window
- ~SchemeUns~, un-selected window
- ~SchemeHid~, hidden tag/window
- ~SchemeInv~, used for showselmon patch, only the selected monitor will have the main color
- ~SchemeUnf~, used for focused windows on unfocused monitor

#+begin_src c
// Colors
static const char col_gray1[]       = "#222222";
static const char col_gray2[]       = "#444444";
static const char col_gray3[]       = "#bbbbbb";
static const char col_gray4[]       = "#eeeeee";
static const char col_gray5[]       = "#151515";
static const char col_black[]       = "#000000";
static const char col_burgundy[]    = "#a93226";
static const char col_burgundy2[]    = "#800020";
static const char col_burgundy3[]    = "#34000d";
static const char col_cyan[]        = "#005577";

static const char *colors[][3]      = {
  /*               fg          bg             border   */
  [SchemeNorm] = { col_gray3,  col_gray1,     col_black },
  [SchemeSel]  = { col_gray4,  col_burgundy2,  col_burgundy2  },
  [SchemeUns]  = { col_gray2,  col_gray1,     col_black },
  [SchemeUnf]  = { col_gray4,  col_gray1,  col_black  },
  [SchemeHid]  = { col_gray5,  col_gray1,     col_black  },
  [SchemeInv]  = { col_gray3,  col_gray1,     col_black },
};
#+end_src

** Layout symbols
The symbol appears in the top to indicate the arrange function. The first entry of ~layouts~ is the default. No layout function, ~NULL~, means floating behaviour.

#+begin_src c
// Layout symbols
/* first entry is default */
static const Layout layouts[] = {
  /* symbol     arrange function */
  { "[M]",      monocle },
  { "[]=",      tile },
  /* { "><>",      NULL },    no layout function means floating behavior. */
};
#+end_src

* Tagging
** Tag names
By default, tags are numbered 1-9. Can be changed to icons, depending on use case.

#+begin_src c
/* TAGGING */

// Tag names
static const char *tags[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9" };
#+end_src

** Tag labels
- ~ptagf~, format of a tag label.
- ~etagf~, format of an empty tag. Though, our dwm is patched to hide empty tags.
- ~lcaselbl~, ~0~ means tag labels are default. ~1~ means make tag label lowercase.

#+begin_src c
// Tag labels
static const char ptagf[] = "[%s %s]";  /* format for tag label in use */
static const char etagf[] = "[%s]";     /* format for empty tag labe l */
static const int lcaselbl = 0;          /* 0, tag labels default. 1, tag labels lowercase. */
#+end_src

** Default for applications
- Default tag mask is ~0~, which means the currently viewed tag.
- Default mode is tiled so ~isfloating~ is ~False~ or ~0~.

#+begin_src c
// Tag defaults for applications
static const Rule rules[] = {
  /* xprop(1):
   ,*  WM_CLASS(STRING) = instance, class
   ,*  WM_NAME(STRING) = title
   ,*/
  /* class      instance    title       tags mask     isfloating   monitor */
  { "steam",    NULL,       NULL,       0,            0,           -1 },
};
#+end_src

*** How to check the properties of a client
Use the following script to get this information using ~xprop~,

#+begin_src bash :tangle no
xprop | awk '
	/^WM_CLASS/{sub(/.* =/, "instance:"); sub(/,/, "\nclass:"); print}
	/^WM_NAME/{sub(/.* =/, "title:"); print}'
#+end_src

** Window following
The following is for the [[https://dwm.suckless.org/patches/windowfollow/][windowfollow]] patch. When a window is assigned a new tag or monitor, will follow the window.

#+begin_src c
// Window following
#define WFACTIVE '>'
#define WFINACTIVE 'v'
#define WFDEFAULT WFACTIVE
#+end_src

* Layout options
** Master and focus
- ~mfact~, factor of master area size. Range from 0.05-0.95.
- ~nmaster~, number of clients in master area.
- ~resizehints~, ~1~ means respect size hints in tiled resizals.
- ~lockfullscreen~, ~1~ will force focus on the fullscreen window.

#+begin_src c
/* LAYOUT OPTIONS */

// Master and focus
static const float mfact     = 0.5;   /* size of master area */
static const int nmaster     = 1;     /* number of clients in master area */
static const int resizehints = 1;     /* 1, respect size hints in tiled resizal */
static const int lockfullscreen = 0;  /* 1, force focus on fullscreen window */
#+end_src

* Shortcuts
** Definitions
*** Modifier definitions
Currently ~MODKEY~ and ~SUPKEY~ reference ~Mod1Mask~ and ~Mod4Mask~, which correlate to the "Alt" and "Super" keys. You can execute ~xmondmap~ in a shell to see what buttons are mapped to which mod. Currently, our options are:
- ~LockMask~, Caps Lock
- ~ShiftMask~, Shift keys
- ~ControlMask~, control keys
- ~Mod1Mask~, Alt keys
- ~Mod3Mask~, Super keys
- ~Mod4Mask~, Super keys

#+begin_src c
/* SHORTCUTS */

// Modifier definitions
#define MODKEY Mod1Mask  /* Alt key */
#define SUPKEY Mod4Mask  /* GUI key */
#+end_src

*** Tagkeys
~TAGKEYS~ defines tag behaviors depending on which number you press.
- ~view~, changes which tag is viewed.
- ~toggleview~, allows you to select multiple tags to be viewed.
- ~tag~, applies a tag number to a window.
- ~toggletag~, allows you to assign multiple tag numbers to a window.

#+begin_src c
// Tagkeys
#define TAGKEYS(KEY,TAG)                                                \
  { SUPKEY,                       KEY,      view,           {.ui = 1 << TAG} }, \
  { SUPKEY|ControlMask,           KEY,      toggleview,     {.ui = 1 << TAG} }, \
  { SUPKEY|ShiftMask,             KEY,      tag,            {.ui = 1 << TAG} }, \
  { SUPKEY|ControlMask|ShiftMask, KEY,      toggletag,      {.ui = 1 << TAG} },
#+end_src

Helper for spawning shell commands in the pre dwm-5.0 fashion.

*** Shell command helper
#+begin_src c
// Shell command helper
#define SHCMD(cmd) { .v = (const char*[]){ "/bin/sh", "-c", cmd, NULL } }
#+end_src

** Aliases
Aliases for more complicated shell commands. Note that commands and flags can be deliminated in the ~{}~ with commas, ~,~.

#+begin_src c
/* Aliases */
// Default
static char dmenumon[2] = "0"; /* component of dmenucmd, manipulated in spawn() */
static const char *dmenucmd[] = { "dmenu_run", "-m", dmenumon, "-p", "boscOS:", NULL };  /* dmenu */
static const char *termcmd[]  = { "alacritty", NULL };                                   /* terminal of choice */
static const char *slock[]  = { "slock", NULL };                                         /* lock screen */
static const char *screenCapture[]  = { "flameshot","gui", NULL };                       /* screen capture */

// App launcher
static const char *emacs[]  = { "emacsclient","-c","-a","''", NULL }; /* opens emacs as client, or starts daemon */
static const char *copyq[]  = { "copyq","menu", NULL }; /* shows copyq window */

// Dmenu
static const char dmpower[] = "bash $HOME/.dotfiles/dmenu/scripts/dmpower"; /* power options */
static const char dmnix[] = "bash $HOME/.dotfiles/dmenu/scripts/dmnix"; /* nix commands */
static const char dmfirefox[] = "bash $HOME/.dotfiles/dmenu/scripts/dmfirefox"; /* select specific firefox profile */

// Media controls
static const char *mutecmd[] = { "amixer", "-q", "set", "Master", "toggle", NULL };            /* mute */
static const char *volupcmd[] = { "amixer", "-q", "set", "Master", "5%+", "unmute", NULL };    /* volume up */
static const char *voldowncmd[] = { "amixer", "-q", "set", "Master", "5%-", "unmute", NULL };  /* volume down */
static const char *miccmd[] = { "amixer", "set", "Capture", "toggle", NULL };                  /* toggle mic */
static const char *medplaypausecmd[] = { "playerctl", "play-pause", NULL };                    /* play/pause */
static const char *mednextcmd[] = { "playerctl", "next", NULL };                               /* next */
static const char *medprevcmd[] = { "playerctl", "previous", NULL };                           /* previous */

// Brightness
static const char *brupcmd[] = { "brightnessctl", "set", "10%+", NULL };    /* brightness up */
static const char *brdowncmd[] = { "brightnessctl", "set", "10%-", NULL };  /* brightness down */
#+end_src

** Keyboard shortcuts
You can find the ~key~ by running ~xev~ in a terminal and noting the event when you press a key in the window that appears.

*** Additional modules
- ~X11/XF86keysym.h~ allows dwm to listen for XF86 keys.

#+begin_src c
/* Additional modules */
#include <X11/XF86keysym.h> /* allows dwm to listen for XF86 keys */
#+end_src

*** Default shortcuts
#+begin_src c
/* Keyboard Shortcuts */
static const Key keys[] = {
  /* modifier                     key        function        argument */
  // Default
  { SUPKEY,                       XK_r,      spawn,          {.v = dmenucmd } },       /* open dmenu */
  { SUPKEY,                       XK_Return, spawn,          {.v = termcmd } },        /* open terminal */
  { SUPKEY,                       XK_l,      spawn,          {.v = slock } },          /* lock screen */
  { SUPKEY,                       XK_Print,  spawn,          {.v = screenCapture } },  /* screen capture */
  { SUPKEY,                       XK_b,      togglebar,      {0} },                    /* toggle status bar */
  { SUPKEY|ShiftMask,                       XK_w,      killclient,     {0} },                    /* close window */

  // Media controls
  { 0, XF86XK_AudioMute, spawn, {.v = mutecmd } },            /* toggle mute */
  { 0, XF86XK_AudioLowerVolume, spawn, {.v = voldowncmd } },  /* volume up */
  { 0, XF86XK_AudioRaiseVolume, spawn, {.v = volupcmd } },    /* volume down */
  { 0, XF86XK_AudioPlay, spawn, {.v = medplaypausecmd } },    /* play/pause */
  { 0, XF86XK_AudioNext, spawn, {.v = mednextcmd } },         /* next */
  { 0, XF86XK_AudioPrev, spawn, {.v = medprevcmd } },         /* previous */

  // Brightness controls
  { 0, XF86XK_MonBrightnessUp, spawn, {.v = brupcmd} },       /* brightness up */
  { 0, XF86XK_MonBrightnessDown, spawn, {.v = brdowncmd} },   /* brightness down */
#+end_src

*** Programs shortcuts
#+begin_src c
  // Programs
  { SUPKEY,                       XK_e,      spawn,          {.v = emacs } },  /* opens emacs as client, if not start daemon */
  { SUPKEY,                       XK_v,      spawn,          {.v = copyq } },  /* opens emacs as client, if not start daemon */
#+end_src
*** Sunshine shortcuts
In the Sunshine applications, we are able to use shortcuts that uses the Gui key. This is the workaround.
#+begin_src c
  // For Sunshine
  { MODKEY|ControlMask|ShiftMask,                       XK_r,      spawn,          {.v = dmenucmd } },       /* open dmenu, for use in sunshine */
  { MODKEY|ControlMask|ShiftMask,                       XK_b,      togglebar,      {0} },                    /* toggle status bar */
  { MODKEY|ControlMask|ShiftMask,                       XK_l,      spawn,          {.v = slock } },          /* lock screen */
#+end_src
*** Dmenus
Opens various dmenu scripts for additional options.

#+begin_src c
  // Dmenu
  { SUPKEY|ShiftMask,             XK_q,      spawn,          SHCMD(dmpower) },  /* power options */
  { SUPKEY|ShiftMask,             XK_n,      spawn,          SHCMD(dmnix) },    /* nix menu */
  { SUPKEY|ShiftMask,             XK_f,      spawn,          SHCMD(dmfirefox) },    /* select specific firefox profile */
#+end_src

*** Select which window to focus

#+begin_src c
  // Focus
  /* Cycle between visible windows */
  { SUPKEY,                       XK_j,      focusstackvis,  {.i = +1 } },
  { SUPKEY,                       XK_k,      focusstackvis,  {.i = -1 } },
  /* Cycle with hidden windows as well */
  { SUPKEY|ShiftMask,             XK_j,      focusstackhid,  {.i = +1 } },
  { SUPKEY|ShiftMask,             XK_k,      focusstackhid,  {.i = -1 } },
#+end_src

*** Hide & Show windows
#+begin_src c
  { SUPKEY,                       XK_h,      hide,           {0} },  /* hide window */
  { SUPKEY,                       XK_s,      show,           {0} },  /* show window */
  { SUPKEY|ShiftMask,             XK_s,      showall,        {0} },  /* show all windows */
#+end_src

*** Configure Layout shortcuts
**** Set layout
#+begin_src c
  // Alignment
  { SUPKEY,                       XK_m,      setlayout,      {.v = &layouts[0]} },  /* switch to monocle mode */
  { SUPKEY,                       XK_t,      setlayout,      {.v = &layouts[1]} },  /* switch to tile mode */
  /* { SUPKEY,                       XK_f,      setlayout,      {.v = &layouts[1]} },  switch to float mode */
  { SUPKEY,                       XK_space,  setlayout,      {0} },                 /* previous mode */
  { SUPKEY|ShiftMask,             XK_space,  togglefloating, {0} },                 /* toggle window floating */
#+end_src
**** Tile mode specific
***** Master
#+begin_src c
  // Tile windows \\

  // Master
  { SUPKEY|ShiftMask,                       XK_i,      incnmaster,     {.i = +1 } },  /* increase number of clients in master area */
  { SUPKEY|ShiftMask,                       XK_u,      incnmaster,     {.i = -1 } },  /* decrease number of clients in master area */
  { SUPKEY,                       XK_u,      setmfact,       {.f = -0.05} },          /* increase size of master area */
  { SUPKEY,                       XK_i,      setmfact,       {.f = +0.05} },          /* decrease size of master area */
  { SUPKEY,                       XK_o, zoom,           {0} },                        /* swap primary window */
#+end_src

***** Gaps
#+begin_src c
  // Layout \\

  // Gaps
  { SUPKEY,                       XK_minus,  setgaps,        {.i = -1 } },  /* decrease gap width */
  { SUPKEY|ShiftMask,             XK_equal,  setgaps,        {.i = +1 } },   /* increase gap width*/
  { SUPKEY,                       XK_equal,  setgaps,        {.i = 0  } },      /* reset gap width */
#+end_src

**** Floating mode specific
***** Move
#+begin_src c
  // Floating windws \\

  // Move
  { SUPKEY,                       XK_Down,   moveresize,     {.v = "0x 25y 0w 0h" } },   /* move window down */
  { SUPKEY,                       XK_Up,     moveresize,     {.v = "0x -25y 0w 0h" } },  /* move window up */
  { SUPKEY,                       XK_Right,  moveresize,     {.v = "25x 0y 0w 0h" } },   /* move window right */
  { SUPKEY,                       XK_Left,   moveresize,     {.v = "-25x 0y 0w 0h" } },  /* move window left */

  // Move (to edge)
  { SUPKEY|ControlMask,           XK_Up,     moveresizeedge, {.v = "t"} },  /* snap to top edge */
  { SUPKEY|ControlMask,           XK_Down,   moveresizeedge, {.v = "b"} },  /* snap to bottom edge */
  { SUPKEY|ControlMask,           XK_Left,   moveresizeedge, {.v = "l"} },  /* snap to left edge */
  { SUPKEY|ControlMask,           XK_Right,  moveresizeedge, {.v = "r"} },  /* snap to right edge */
#+end_src

***** Resiz,e
#+begin_src c
  // Resize
  { SUPKEY|ShiftMask,             XK_Down,   moveresize,     {.v = "0x 0y 0w 25h" } },   /* increase height */
  { SUPKEY|ShiftMask,             XK_Up,     moveresize,     {.v = "0x 0y 0w -25h" } },  /* decrease height */
  { SUPKEY|ShiftMask,             XK_Right,  moveresize,     {.v = "0x 0y 25w 0h" } },   /* increase width */
  { SUPKEY|ShiftMask,             XK_Left,   moveresize,     {.v = "0x 0y -25w 0h" } },  /* decrease width */

  // Resise (to edge)
  { SUPKEY|ControlMask|ShiftMask, XK_Up,     moveresizeedge, {.v = "T"} },  /* snap height to top edge */
  { SUPKEY|ControlMask|ShiftMask, XK_Down,   moveresizeedge, {.v = "B"} },  /* snap height to bottom edge */
  { SUPKEY|ControlMask|ShiftMask, XK_Left,   moveresizeedge, {.v = "L"} },  /* snap width to left edge */
  { SUPKEY|ControlMask|ShiftMask, XK_Right,  moveresizeedge, {.v = "R"} },  /* snap width to right edge */
#+end_src

*** Multi-monitor
#+begin_src c
  // Multi-monitor
  { SUPKEY,                       XK_comma,  focusmon,       {.i = -1 } },  /* focus monitor on left */
  { SUPKEY,                       XK_period, focusmon,       {.i = +1 } },  /* focus monitor on right */
  { SUPKEY|ShiftMask,             XK_comma,  tagmon,         {.i = -1 } },  /* move window to monitor on left */
  { SUPKEY|ShiftMask,             XK_period, tagmon,         {.i = +1 } },  /* move window to monitor on right */
#+end_src

*** Tags
- Duplicated shortcuts to move to adjacent tabs were changed to align with Window shotcuts with similar behavior (i.e., move between workspaces).

#+begin_src c
  // Tags
  { SUPKEY,                       XK_Tab,    view,           {0} },          /* view previous tag */
  { SUPKEY,                       XK_0,      view,           {.ui = ~0 } },  /* view all tags*/
  { SUPKEY|ShiftMask,             XK_0,      tag,            {.ui = ~0 } },  /* assign all tags to window */
  { SUPKEY,                       XK_Page_Down,  viewnext,       {0} },          /* view tag to the right */
  { SUPKEY,                       XK_Page_Up,   viewprev,       {0} },          /* view tag to the left */
  { SUPKEY|ShiftMask,             XK_Page_Down,  tagtonext,      {0} },          /* assign to tag to the right */
  { SUPKEY|ShiftMask,             XK_Page_Up,   tagtoprev,      {0} },          /* assign to tag to the left */
  { SUPKEY,                       XK_n,      togglefollow,   {0} },

  // Default tag controls
  TAGKEYS(                        XK_1,                      0)
  TAGKEYS(                        XK_2,                      1)
  TAGKEYS(                        XK_3,                      2)
  TAGKEYS(                        XK_4,                      3)
  TAGKEYS(                        XK_5,                      4)
  TAGKEYS(                        XK_6,                      5)
  TAGKEYS(                        XK_7,                      6)
  TAGKEYS(                        XK_8,                      7)
  TAGKEYS(                        XK_9,                      8)
};
#+end_src

** Mouse buttons
Can be:
- ~ClkTagBar~, clicking tags.
- ~ClkLtSymbol~, clicking layout symbol.
- ~ClkStatusText~,
- ~ClkWinTitle~, clicking window title.
- ~ClkClientWin~, clicking client window.
- ~ClkRootWin~, clicking root window.

#+begin_src c
// Mouse functionality \\

static const Button buttons[] = {
  /* click                event mask      button          function        argument */
  { ClkLtSymbol,          0,              Button1,        setlayout,      {0} },
  { ClkLtSymbol,          0,              Button3,        setlayout,      {.v = &layouts[2]} },
  { ClkWinTitle,          0,              Button1,        togglewin,      {0} },
  { ClkFollowSymbol,      0,              Button1,        togglefollow,   {0} },
  { ClkWinTitle,          0,              Button2,        zoom,           {0} },
  { ClkStatusText,        0,              Button2,        spawn,          {.v = termcmd } },
  { ClkClientWin,         SUPKEY,         Button1,        movemouse,      {0} },
  { ClkClientWin,         SUPKEY,         Button2,        togglefloating, {0} },
  { ClkClientWin,         SUPKEY,         Button3,        resizemouse,    {0} },
  { ClkTagBar,            0,              Button1,        view,           {0} },
  { ClkTagBar,            0,              Button3,        toggleview,     {0} },
  { ClkTagBar,            SUPKEY,         Button1,        tag,            {0} },
  { ClkTagBar,            SUPKEY,         Button3,        toggletag,      {0} },
};
#+end_src
