#! /usr/bin/env bash
#
# Script name: dmpower
# Description: Choose from a list of power options

# Options array
declare -a options=(
  "Yes"
  "No"
)

# Number of items in options array
optionsSize=${#options[@]}

# Piping above array into dmenu
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l $optionsSize -p 'Confirm Quit:')

if [ "$choice" == "Yes" ]; then
  killall dwm
fi
