# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2026.2.25";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/3c/c17fb3ca2d9c3acff52e30b309f538586f9f5b9c9cf454f3845fc9af4881/certifi-2026.2.25-py3-none-any.whl";
      sha256 = "1yphsvqqmnynspj9ch1ynx3ccqwpgacs8lifqkqr9n9a83j94xh2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/13/69/33ddede1939fdd074bce5434295f38fae7136463422fe4fd3e0e89b98062/charset_normalizer-3.4.4.tar.gz";
      sha256 = "06p20hsbfmg9pdc307ffnb7nwfmlwyw06dp4423z4d8w262pjlwl";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/61/66938bbb5fc52dbdf84594873d5b51fb1f7c7794e9c0f5bd885f30bc507b/idna-3.11-py3-none-any.whl";
      sha256 = "1sipr9kdjcmwjm3lc6dx83qk6j4dq7lnyvhy15jazvwxkps8f6kp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.32.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/db/4254e3eabe8020b458f1a747140d32277ec7a271daf1d235b70dc0b4e6e3/requests-2.32.5-py3-none-any.whl";
      sha256 = "1dpz38b6lnn8fcad7kfiagagbc3djy3f35a24qrdakx36x3gjqi4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "stashapi" = super.buildPythonPackage rec {
    pname = "stashapi";
    version = "0.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/98/c6/efa95a6815653b0198dbe32571c648428fc29f79ba8b6188b205132d0ca7/stashapi-0.0.0-py3-none-any.whl";
      sha256 = "00hji88zav4jgyz6d8a0vz4gs2s53j9f5ich6j0s9qihxsapmxv6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."requests"
    ];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "2.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/08/aaaad47bc4e9dc8c725e68f9d04865dbcb2052843ff09c97b08904852d84/urllib3-2.6.3-py3-none-any.whl";
      sha256 = "1m5cn1yd6gvd8dax7fyp36wngx5hlxf25zcvgplb5pskwlij69xz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
